# Site settings
title: Connor Salmon
email: connor.louis.salmon@gmail.com
description: Experienced UX Designer & Researcher > # this means to ignore newlines until "baseurl:"
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "ConnorSalmon.github.io" # the base hostname & protocol for your site

# User setting
owner: Connor Salmon
email: connor.salmon@gmail.com
github_username: ConnorSalmon
address: San Francisco, California
  # Feel free to add more lines here 
telephone: +1 (415)209-4584 
copyright: Connor Salmon / UX Design / 2019

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman